spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: COURSE
    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
mybatis:
  mapper-locations: classpath:mappers/*.xml