spring:
  datasource:
    url: jdbc:mysql://localhost:3306/join
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none