spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: none
        secure: true
#  ssl:
#    key-store: /Users/guybrush/git/SpringFramework/course-spring/shopping-project/src/main/resources/keystore.p12
#    key-store-password: 1qaz2wsx
#    key-store-type: PKCS12
#    key-alias: tomcat